### ISSUE TITLE
python gcs client use generation as 0 when it is None, which is not supported/implemented yet. 

### ISSUE THREAD

**Issue by kc-panw** [fsouza/fake-gcs-server#198] opened 2020-03-20 23:46 UTC
GCS client forms the GET url with param `generation=0` which is not implemented in the server.
So, if it's not implemented, the quick fix may be replacing all

`if generationStr != ""`

to 
 
`if generationStr != "" && generationStr != "0"`

so that it uses `Server.GetObject()`

otherwise, get/download object will fail. We can easily reproduce this by running example code.

Just wonder if `GetObjectWithGeneration()` will be implemented soon or any other better fix?

**Comment by fsouza** [comment] 2020-04-20 21:07
Hi @kc-panw, thanks for reporting and sorry for the delayed response. There aren't any plans for implementing `GetObjectWithGeneration()` at the moment, unfortunately.

Regarding generation being 0, I just pushed a fix.

**Comment by linjun9** [comment] 2020-05-06 22:08
Hi @fsouza, I ran into the same issue again by running the python sample code. The problem is you only update the `getObject` function, but there are `rewriteObject` and `downloadObject` as well. 

Is there a reason that you don't want to update those two functions? Thanks in advance.

**Comment by fsouza** [comment] 2020-05-06 22:19
It was an oversight. Will push a fix, thanks for pinging me!

**Closed** 2020-05-06 22:36 UTC
