### ISSUE TITLE
python gcs client will throw ValueError because of wrong timestamp format

### ISSUE THREAD

**Issue by kc-panw** [fsouza/fake-gcs-server#199] opened 2020-03-20 23:51 UTC
The python GCS client somehow takes its format very similar to RFC3339 but not exactly the same so it will throw.

The format it uses is actually:

`"2006-01-02T15:04:05.999999Z07:00"`

not

`time.RFC3339`

 would this be fixed?

**Comment by fsouza** [comment] 2020-03-21 03:08
@kc-panw hey there, thanks for reporting this issue. It can definitely be fixed. Can you provide a reproducer, just so we can write a test to prevent regressions?

Thanks!

**Comment by linjun9** [comment] 2020-05-07 02:37
yea, I'm getting the same problem. You can reproduce by running the following sample code.

The problem is it using RFC3339Microsecond in python GCS client, but it's using RFC3339 in `fake-gcs-server`. It requires following format `2006-01-02T15:04:05.999999Z07:00`
```
import os

import requests
import urllib3
from google.api_core.client_options import ClientOptions
from google.auth.credentials import AnonymousCredentials
from google.cloud import storage

EXTERNAL_URL = os.getenv("EXTERNAL_URL", "https://127.0.0.1:4443")
PUBLIC_HOST = os.getenv("PUBLIC_HOST", "storage.gcs.127.0.0.1.nip.io:4443")

storage.blob._API_ACCESS_ENDPOINT = "https://" + PUBLIC_HOST
storage.blob._DOWNLOAD_URL_TEMPLATE = (
    u"%s/download/storage/v1{path}?alt=media" % EXTERNAL_URL
)
storage.blob._BASE_UPLOAD_TEMPLATE = (
    u"%s/upload/storage/v1{bucket_path}/o?uploadType=" % EXTERNAL_URL
)
storage.blob._MULTIPART_URL_TEMPLATE = storage.blob._BASE_UPLOAD_TEMPLATE + u"multipart"
storage.blob._RESUMABLE_URL_TEMPLATE = storage.blob._BASE_UPLOAD_TEMPLATE + u"resumable"

my_http = requests.Session()
my_http.verify = False  # disable SSL validation
urllib3.disable_warnings(
    urllib3.exceptions.InsecureRequestWarning
)  # disable https warnings for https insecure certs

client = storage.Client(
    credentials=AnonymousCredentials(),
    project="test",
    _http=my_http,
    client_options=ClientOptions(api_endpoint=EXTERNAL_URL),
)


bucket = client.bucket('sample-bucket')
b = bucket.get_blob('test_file.txt')
s = b.download_to_filename('/test.txt')
```

**Comment by fsouza** [comment] 2020-05-11 02:52
@linjun9 awesome, thanks for the reproducer! The fix for this is small (use ``time.RFC3339Nano` instead of `time.RFC3339`), but writing a test may be trickier. I can give it a shot later this week.

**Comment by linjun9** [comment] 2020-05-11 12:58
@fsouza  I tryied `time.RFC3339Nano`. It doesn't work, since `RFC3339Nano` gives us 9 decimal places, we only need 6 decimal places. Not a Golang expert, but yea, feel free to try it out. Thanks 👍

**Closed** 2020-07-21 03:52 UTC

**Comment by chrisK824** [comment] 2024-05-11 19:33
Hi @fsouza , thanks for this awesome project!

I have stumbled on the above issue. I am not sure if this has been re-introduced at some stage due to python client changes, but it is breaking in my trials. I am using python3.12 and latest version (1.49) of the emulator.

Here is a reproducing script:

```
from google.api_core.client_options import ClientOptions
from google.auth.credentials import AnonymousCredentials
from google.cloud import storage


client = storage.Client(
    credentials=AnonymousCredentials(),
    project="test",
    client_options=ClientOptions(api_endpoint="http://localhost:6000"),
)


bucket = client.create_bucket('sample-bucket')
b = bucket.blob("test")

with b.open('wb') as f:
    f.write('test'.encode())

updated_b = bucket.get_blob('test')

print(updated_b.updated)
```

this spits out:

```
➜  example python3.9 example.py
Traceback (most recent call last):
  File "/Users/chriskarvouniaris/Desktop/example/example.py", line 26, in <module>
    print(updated_b.updated)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 4224, in updated
    return _rfc3339_nanos_to_datetime(value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py", line 273, in _rfc3339_nanos_to_datetime
    raise ValueError(
ValueError: Timestamp: '2024-05-11T22:29:31.335823+03:00', does not match pattern: '\n    (?P<no_fraction>\n        \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}  # YYYY-MM-DDTHH:MM:SS\n    )\n    (                                        # Optional decimal part\n     \\.                                      # decimal point\n     (?P<nanos>\\d{1,9})                      # nanoseconds, maybe truncated\n    )?\n    Z     
```
