### ISSUE TITLE
version tag for latest version

### ISSUE THREAD

**Issue by avihaybar** [fsouza/fake-gcs-server#489] opened 2021-04-27 10:52 UTC
Hi, great docker! we found it very useful.

However, one thing we didn't find on DockerHub is a version tag for the latest version.
(we prefer to pin down a version and not use the 'latest' tag).
is it possible create such a tag (the same way we could pull v1.21.2)

**Comment by fsouza** [comment] 2021-04-27 12:07
🤔 GitHub Actions should be doing that automatically. Will investigate what's going on and manually push.

**Comment by fsouza** [comment] 2021-04-27 13:16
Ok, I see what the issue is, we're doing a naked `docker push` and that no longer pushes all tags. Will fix the script and manually push the tags.

**Comment by fsouza** [comment] 2021-04-27 13:33
This is now fixed. All tags are pushed and going forward GitHub Actions should do it for us properly.

If anyone is interested in auditing what I did, this is the script I used for each tag:

```
％ cat ~/regen-tag.bash
#!/usr/bin/env bash

set -euo pipefail

tag=${1}

git checkout "${tag}"
env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
env GITHUB_REF="refs/tags/${tag}" bash ci/docker-build.sh
```

And these are the tags I pushed:

```
％ cat ~/tags
v1.22.0
v1.22.1
v1.22.2
v1.22.3
v1.22.4
v1.22.5
v1.22.6
v1.22.7
v1.23.0
v1.23.1
v1.24.0
```

To run the script:

```
％ cat ~/tags | xargs -I @ ~/regen-tag.bash @
```

**Closed by fsouza** 2021-04-27 13:33 UTC
Labels: bug, docker

**Comment by avihaybar** [comment] 2021-04-27 15:00
Thanks! 
Really appreciate it
